# Generated by Django 4.0.4 on 2022-07-04 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=65)),
                ('last_name', models.CharField(max_length=65)),
                ('birth_date', models.DateField()),
                ('mobile_num', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('registration', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=65)),
                ('position', models.CharField(max_length=65)),
                ('sphere', models.CharField(max_length=100)),
                ('min_salary', models.IntegerField()),
                ('busyness', models.CharField(default='', max_length=65)),
                ('work_graph', models.CharField(max_length=65)),
                ('about', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=65)),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('sex', models.CharField(max_length=65)),
                ('birth_date', models.DateField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('cvattr_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.cvattr')),
                ('degree', models.CharField(max_length=65)),
                ('establishment', models.CharField(max_length=65)),
                ('faculty', models.CharField(max_length=65)),
                ('specialization', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
            bases=('employee.cvattr',),
        ),
        migrations.CreateModel(
            name='KnownLanguage',
            fields=[
                ('cvattr_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.cvattr')),
                ('language', models.CharField(max_length=25)),
                ('level', models.CharField(max_length=65)),
            ],
            bases=('employee.cvattr',),
        ),
        migrations.CreateModel(
            name='KnownProgram',
            fields=[
                ('cvattr_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.cvattr')),
                ('program', models.CharField(max_length=65)),
            ],
            bases=('employee.cvattr',),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('cvattr_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.cvattr')),
                ('position', models.CharField(max_length=65)),
                ('org_name', models.CharField(max_length=100)),
                ('responsibilities', models.TextField()),
                ('start_year', models.CharField(max_length=65)),
                ('end_year', models.CharField(max_length=65)),
            ],
            bases=('employee.cvattr',),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='cv',
            name='suitable_vacancies',
            field=models.ManyToManyField(blank=True, to='vacancy.vacancy'),
        ),
        migrations.CreateModel(
            name='ChosenVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='ChosenCv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.cv')),
                ('hirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
