# Generated by Django 4.0.4 on 2022-07-04 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=65)),
                ('sphere', models.CharField(max_length=100)),
                ('min_salary', models.IntegerField(default=0)),
                ('max_salary', models.IntegerField()),
                ('registration', models.CharField(default='не имеет значения', max_length=100)),
                ('experience', models.CharField(max_length=65)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('sex', models.CharField(default='не имеет значения', max_length=65)),
                ('education', models.CharField(max_length=65)),
                ('responsibilities', models.TextField()),
                ('work_terms', models.TextField()),
                ('busyness', models.CharField(default='', max_length=65)),
                ('work_graph', models.CharField(max_length=65)),
                ('payment', models.TextField(default='')),
                ('views', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NeededLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=25)),
                ('level', models.CharField(max_length=65)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy')),
            ],
        ),
    ]
